version: '0.1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
init:
 - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
build_script:
- appveyor-retry dotnet restore -v Minimal
- dotnet build "src\Uri" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet pack "src\Uri" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
test_script:
- dotnet build "test\Uri.Tests" -c %CONFIGURATION% --no-dependencies
- dotnet test "test\Uri.Tests" -c %CONFIGURATION% --no-build
artifacts:
  - path: artifacts\**\*.*
deploy:
 - provider: NuGet
   server: https://www.myget.org/F/ci/api/v2/package
   api_key:
     secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
   skip_symbols: false
   symbol_server: https://www.myget.org/F/ci/api/v2/package
cache:
 - '%USERPROFILE%\.nuget\packages'